experiment_name: "config_test"

data:
  image_size: 32     # 모델 구조(UNet)와 직결 (반드시 필요)
  channels: 3        # 1(흑백) -> 3(컬러)로 변경 (반드시 필요)

model:
  dim: 128            # 모델의 기본 두께 (Size Mismatch 방지용)
  type: "simple"

diffusion:
  timesteps: 1000    # 확산 단계 (성능의 기본값)

train:
  batch_size: 128    # GPU 메모리에 맞춰 조절
  lr: 2e-7           # 학습률
  epochs: 3        # 최소한의 형태가 잡히는 시점
  ema_beta: 0.995