experiment_name: "alice_diffusion_v1"

# [데이터 설정]
data:
  dataset: "alice"   # 여기를 'alice'로 바꾸면 끝!

# [모델 설정]
model:
  seq_len: 64
  dim: 128
  depth: 6
  heads: 4
  dropout: 0.1

# [확산 설정]
diffusion:
  timesteps: 1000

# [학습 설정]
train:
  batch_size: 1024
  lr: 0.001
  epochs: 200
  save_interval: 10